apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  generation: 1
  name: dcsp-devops-ingress
  namespace: dcsp-devops
spec:
  rules:
  - host: dcsp-devops.zmon.cloud
    http:
      paths:
      - backend:
          serviceName: listener-dcsp-devops
          servicePort: 18080
        path: /
